let DATA={categorias:[],produtos:[]};
const $=s=>document.querySelector(s);
function arr(v){return Array.isArray(v)?v.map(x=>typeof x==='string'?x:(x.item||x.nome||x.value||'')).filter(Boolean):[]}
function getId(){return new URLSearchParams(location.search).get('id')||'carro-gol-g5'}
function cat(id){return DATA.categorias.find(c=>c.id===id)||{nome:id}}
function isGlb(p){return p.glb&&p.glb.toLowerCase().endsWith('.glb')}
function media(p){return isGlb(p)?`<model-viewer src="${p.glb}" poster="${p.imagem}" camera-controls auto-rotate shadow-intensity="1"></model-viewer>`:`<img src="${p.imagem}" alt="${p.nome}">`}
function normalizeProduct(p){return {...p,formatos:arr(p.formatos),compatibilidade:arr(p.compatibilidade),tags:arr(p.tags),inclusos:arr(p.inclusos),detalhes:arr(p.detalhes),galeria:arr(p.galeria)}}
function render(){DATA.produtos=DATA.produtos.map(normalizeProduct);const p=DATA.produtos.find(x=>x.id===getId());if(!p){$('#productPage').innerHTML='<section class="license-section"><h1>Produto não encontrado</h1><a class="btn yellow" href="index.html#catalogo">Voltar ao catálogo</a></section>';return}document.title=p.nome+' | MODELOS BRASIL';$('#productPage').innerHTML=`<section class="detail-layout"><div class="detail-media">${media(p)}</div><aside class="buy-panel"><span class="label ${p.maisVendido?'best':'new'}">${p.maisVendido?'Mais vendido':p.novo?'Novo':'Produto'}</span><h1>${p.nome}</h1><p>${p.subtitulo||p.descricaoCurta||''}</p><span class="price">${p.precoTexto||'Consultar'}</span><div class="buy-actions"><a class="btn yellow" href="mailto:fabricio.souza2088@gmail.com?subject=Compra - ${encodeURIComponent(p.nome)}">Comprar agora</a><a class="btn dark" href="mailto:fabricio.souza2088@gmail.com?subject=Dúvida - ${encodeURIComponent(p.nome)}">Falar com vendedor</a></div><div class="spec"><div><span>Categoria</span><strong>${cat(p.categoria).nome}</strong></div><div><span>Formatos</span><strong>${arr(p.formatos).join(' / ')}</strong></div><div><span>Tamanho</span><strong>${p.tamanho||''}</strong></div><div><span>Tipo</span><strong>${p.tipo||''}</strong></div><div><span>Detalhe</span><strong>${p.poligonos||''}</strong></div></div></aside></section><section class="info-grid"><article class="info-panel wide"><h2>Descrição completa</h2><p>${p.descricaoCompleta||p.descricaoCurta||''}</p></article><article class="info-panel"><h2>Compatibilidade</h2><ul>${arr(p.compatibilidade).map(i=>`<li>${i}</li>`).join('')}</ul></article><article class="info-panel"><h2>Arquivos inclusos</h2><ul>${arr(p.inclusos).map(i=>`<li>${i}</li>`).join('')}</ul></article><article class="info-panel"><h2>Detalhes técnicos</h2><ul>${arr(p.detalhes).map(i=>`<li>${i}</li>`).join('')}</ul></article><article class="info-panel"><h2>Licença</h2><p>${p.licenca||'Licença definida pela MODELOS BRASIL.'}</p></article></section>`}
fetch('produtos.json?ts='+Date.now()).then(r=>r.json()).then(d=>{DATA=d;render()}).catch(err=>{$('#productPage').innerHTML='<section class="license-section"><h1>Erro ao carregar produto</h1></section>';console.error(err)});
