const CATEGORIAS = [
  { id: "todos", nome: "Todos", descricao: "Todos os assets da loja" },
  { id: "carros", nome: "Carros", descricao: "Veículos leves brasileiros" },
  { id: "caminhoes", nome: "Caminhões", descricao: "Caminhões e veículos pesados" },
  { id: "onibus", nome: "Ônibus", descricao: "Transporte urbano e rodoviário" },
  { id: "maquinas", nome: "Máquinas", descricao: "Máquinas industriais e agrícolas" },
  { id: "packs", nome: "Packs", descricao: "Pacotes com vários assets" },
  { id: "unreal", nome: "Unreal Engine", descricao: "Assets preparados para Unreal" },
  { id: "gta", nome: "GTA / FiveM", descricao: "Modelos para mods e servidores" },
  { id: "blender", nome: "Blender", descricao: "Arquivos para edição 3D" }
];

const PRODUTOS = [
  {
    id: "carro-gol",
    nome: "Carro Gol",
    subtitulo: "Modelo 3D brasileiro compacto e versátil",
    categoria: "carros",
    tipo: "Modelo individual",
    preco: 89.90,
    precoTexto: "R$ 89,90",
    destaque: true,
    novo: true,
    imagem: "assets/carro_gol.png",
    glb: "glb/carro_gol.glb",
    formatos: ["GLB", "FBX", "OBJ"],
    compatibilidade: ["Blender", "Unreal Engine", "GTA / FiveM"],
    tags: ["Carro", "Brasil", "Game Ready", "Veículo", "Popular"],
    tamanho: "~22 MB",
    poligonos: "Médio detalhe",
    licenca: "Uso pessoal e comercial conforme termos da loja",
    descricaoCurta: "Modelo clássico brasileiro para games, renderização, estudos e simulação.",
    descricaoCompleta: "Modelo 3D de veículo brasileiro, organizado para uso em projetos digitais. Ideal para protótipos, jogos, visualização automotiva, mods e estudos. A estrutura foi pensada para facilitar a edição no Blender e integração em engines.",
    inclusos: ["Arquivo GLB para preview e web", "Arquivo FBX para engines", "Arquivo OBJ para compatibilidade", "Texturas organizadas", "Imagem de capa"],
    detalhes: ["Malha organizada", "Escala padronizada", "Materiais separados", "Pronto para visualização 3D", "Compatível com pipeline web"],
    galeria: ["assets/carro_gol.png", "assets/carro_gol.png", "assets/carro_gol.png"]
  },
  {
    id: "caminhao-volvo",
    nome: "Caminhão Volvo",
    subtitulo: "Caminhão pesado para simulação e projetos automotivos",
    categoria: "caminhoes",
    tipo: "Modelo individual",
    preco: 149.90,
    precoTexto: "R$ 149,90",
    destaque: false,
    novo: true,
    imagem: "assets/caminhao_volvo.png",
    glb: "https://drive.google.com/uc?id=EXEMPLO_DE_ID",
    formatos: ["GLB", "FBX"],
    compatibilidade: ["Blender", "Unreal Engine"],
    tags: ["Caminhão", "Pesado", "Simulação", "Transporte"],
    tamanho: ">25 MB",
    poligonos: "Alto detalhe",
    licenca: "Uso pessoal e comercial conforme termos da loja",
    descricaoCurta: "Modelo de caminhão pesado com entrega por link externo quando necessário.",
    descricaoCompleta: "Asset de caminhão pesado criado para cenas automotivas, simulação logística e projetos de visualização. Arquivos grandes podem ser entregues via link externo seguro.",
    inclusos: ["Arquivo GLB", "Arquivo FBX", "Texturas", "Preview renderizado"],
    detalhes: ["Modelo em escala", "Peças principais separadas", "Indicado para simulação", "Entrega por link externo"],
    galeria: ["assets/caminhao_volvo.png", "assets/caminhao_volvo.png", "assets/caminhao_volvo.png"]
  },
  {
    id: "pack-veiculos-brasil",
    nome: "Pack Veículos Brasil",
    subtitulo: "Pacote inicial de veículos brasileiros para produção",
    categoria: "packs",
    tipo: "Pack",
    preco: 249.90,
    precoTexto: "R$ 249,90",
    destaque: true,
    novo: false,
    imagem: "assets/carro_gol.png",
    glb: "glb/carro_gol.glb",
    formatos: ["GLB", "FBX", "OBJ"],
    compatibilidade: ["Blender", "Unreal Engine", "GTA / FiveM"],
    tags: ["Pack", "Veículos", "Game Ready", "Brasil"],
    tamanho: "Variável",
    poligonos: "Misto",
    licenca: "Uso pessoal e comercial conforme termos da loja",
    descricaoCurta: "Pack demonstrativo com veículos brasileiros para games, engines e visualização.",
    descricaoCompleta: "Pacote pensado para compradores que precisam de vários veículos brasileiros em um único produto. Ideal para iniciar projetos de mapas, protótipos, simulação urbana e catálogos digitais.",
    inclusos: ["Múltiplos modelos", "Formatos populares", "Texturas", "Documentação básica"],
    detalhes: ["Organização por pastas", "Compatibilidade com engines", "Boa base para projetos maiores", "Licença clara de uso"],
    galeria: ["assets/carro_gol.png", "assets/caminhao_volvo.png", "assets/carro_gol.png"]
  },
  {
    id: "onibus-urbano-br",
    nome: "Ônibus Urbano BR",
    subtitulo: "Modelo urbano brasileiro para cenários e simulação",
    categoria: "onibus",
    tipo: "Modelo individual",
    preco: 129.90,
    precoTexto: "R$ 129,90",
    destaque: false,
    novo: false,
    imagem: "assets/carro_gol.png",
    glb: "glb/carro_gol.glb",
    formatos: ["GLB", "FBX"],
    compatibilidade: ["Blender", "Unreal Engine"],
    tags: ["Ônibus", "Urbano", "Transporte", "Brasil"],
    tamanho: "~35 MB",
    poligonos: "Médio detalhe",
    licenca: "Uso pessoal e comercial conforme termos da loja",
    descricaoCurta: "Ônibus urbano brasileiro para ambientação de cidades e projetos de transporte.",
    descricaoCompleta: "Modelo demonstrativo para categoria de ônibus. Substitua os arquivos quando o asset real estiver pronto.",
    inclusos: ["Arquivo GLB", "Arquivo FBX", "Texturas"],
    detalhes: ["Preparado para vitrine", "Ideal para cenários urbanos", "Materiais editáveis"],
    galeria: ["assets/carro_gol.png", "assets/carro_gol.png"]
  }
];
