let DATA={categorias:[],produtos:[]};
const state={search:'',category:'todos',engine:'',type:'',sort:'newest'};
const $=s=>document.querySelector(s);
function arr(v){return Array.isArray(v)?v.map(x=>typeof x==='string'?x:(x.item||x.nome||x.value||'')).filter(Boolean):[]}
function cat(id){return DATA.categorias.find(c=>c.id===id)||{nome:id,icone:'•'}}
function isGlb(p){return p.glb&&p.glb.toLowerCase().endsWith('.glb')}
function media(p){return isGlb(p)?`<model-viewer src="${p.glb}" poster="${p.imagem}" camera-controls auto-rotate shadow-intensity="1"></model-viewer>`:`<img src="${p.imagem}" alt="${p.nome}">`}
function normalizeProduct(p){return {...p,formatos:arr(p.formatos),compatibilidade:arr(p.compatibilidade),tags:arr(p.tags),inclusos:arr(p.inclusos),detalhes:arr(p.detalhes),galeria:arr(p.galeria)}}
function buildCategoryMenu(){const total=DATA.produtos.length;$('#categoryMenu').innerHTML=DATA.categorias.map(c=>{const n=c.id==='todos'?total:DATA.produtos.filter(p=>p.categoria===c.id).length;return `<button class="side-item ${c.id==='todos'?'active':''}" data-category="${c.id}"><span><i>${c.icone||'•'}</i>${c.nome}</span><b>${n}</b></button>`}).join('');document.querySelectorAll('[data-category]').forEach(btn=>btn.onclick=()=>{state.category=btn.dataset.category;document.querySelectorAll('[data-category]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderProducts()})}
function featureCard(p,i){const label=p.maisVendido?'MAIS VENDIDO':p.novo?'NOVO':'DESTAQUE';return `<a class="feature-card" href="produto.html?id=${p.id}"><div class="feature-thumb">${media(p)}</div><div><small>${label}</small><strong>${p.nome}</strong><span>${cat(p.categoria).nome}</span><b>${p.precoTexto||'Consultar'}</b></div></a>`}
function productCard(p){const label=p.maisVendido?'<span class="label best">Mais vendido</span>':p.novo?'<span class="label new">Novo</span>':'<span class="label best">Pack</span>';return `<article class="product-card"><div class="product-media">${media(p)}<span class="heart">♡</span></div><div class="product-body">${label}<h3>${p.nome}</h3><span class="category">${cat(p.categoria).nome}</span><span class="price">${p.precoTexto||'Consultar'}</span><div class="format-row">${arr(p.formatos).slice(0,3).map(f=>`<span>${f}</span>`).join('')}</div><div class="rating"><span>★ ${p.avaliacao||'5.0'} (${p.reviews||'0'})</span><a class="cart-btn" href="produto.html?id=${p.id}" title="Ver detalhes">›</a></div></div></article>`}
function matches(p){const text=[p.nome,p.subtitulo,p.descricaoCurta,cat(p.categoria).nome,p.tipo,...arr(p.tags),...arr(p.formatos),...arr(p.compatibilidade)].join(' ').toLowerCase();const searchOk=text.includes(state.search.toLowerCase());const catOk=state.category==='todos'||p.categoria===state.category;const engOk=!state.engine||arr(p.compatibilidade).includes(state.engine);const typeOk=!state.type||p.tipo===state.type||arr(p.tags).includes(state.type);return searchOk&&catOk&&engOk&&typeOk}
function sortProducts(list){const l=[...list];if(state.sort==='newest')return l.sort((a,b)=>Number(b.novo)-Number(a.novo));if(state.sort==='price-low')return l.sort((a,b)=>(a.preco||0)-(b.preco||0));if(state.sort==='price-high')return l.sort((a,b)=>(b.preco||0)-(a.preco||0));return l.sort((a,b)=>Number(b.destaque)-Number(a.destaque))}
function renderProducts(){const list=sortProducts(DATA.produtos.filter(matches));$('#productGrid').innerHTML=list.length?list.map(productCard).join(''):`<section class="license-section"><h2>Nenhum produto encontrado</h2><p>Tente limpar os filtros ou buscar outro termo.</p></section>`}
function init(){DATA.produtos=DATA.produtos.map(normalizeProduct);buildCategoryMenu();const hero=DATA.produtos.find(p=>p.destaque)||DATA.produtos[0];if(hero)$('#heroVisual').innerHTML=media(hero);const featured=DATA.produtos.filter(p=>p.destaque);$('#featuredList').innerHTML=(featured.length?featured:DATA.produtos).slice(0,3).map(featureCard).join('');$('#globalSearch').addEventListener('input',e=>{state.search=e.target.value;renderProducts()});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderProducts()});document.querySelectorAll('[data-engine]').forEach(b=>b.onclick=()=>{state.engine=b.dataset.engine;renderProducts()});document.querySelectorAll('.channel-card').forEach(b=>b.onclick=()=>{if(b.dataset.channel)state.engine=b.dataset.channel;if(b.dataset.category)state.category=b.dataset.category;renderProducts();location.hash='catalogo'});document.querySelectorAll('[data-type-filter]').forEach(c=>c.onchange=()=>{state.type=c.checked?c.value:'';document.querySelectorAll('[data-type-filter]').forEach(x=>{if(x!==c)x.checked=false});renderProducts()});$('#clearFilters').onclick=()=>{state.search='';state.category='todos';state.engine='';state.type='';$('#globalSearch').value='';document.querySelectorAll('[data-type-filter]').forEach(x=>x.checked=false);document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category==='todos'));renderProducts()};$('#viewAll').onclick=()=>{state.category='todos';state.engine='';state.type='';renderProducts()};renderProducts()}
fetch('produtos.json?ts='+Date.now()).then(r=>r.json()).then(d=>{DATA=d;init()}).catch(err=>{console.error(err);$('#productGrid').innerHTML='<section class="license-section"><h2>Erro ao carregar produtos.json</h2><p>Verifique se o produtos.json está na raiz do repositório.</p></section>'});
